"""Generate TypeScript declarations for CMS modules.

Writes a ``types.d.ts`` next to each ``index.astro`` so the IDE autocompletes
``Astro.props.fields`` from the field list the developer declared, and flags a
typo before the module ever reaches a build.

The types encode the same resolution rule the runtime applies: a ``PROPERTY_*``
field arrives as the *value* of that property on the page's record, not the
property name the editor picked. The name stays reachable through ``rawFields``,
which listing modules need.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from caraer_cli.project.modules_sync import (
    GENERATED_TYPES_FILE,
    LocalModule,
    discover_local_modules,
)
from caraer_cli.project.schema import ProjectConfig

#: Resolved TypeScript type per field type, as the module receives it.
_FIELD_TS_TYPES: dict[str, str] = {
    "SINGLE_LINE": "string",
    "MULTI_LINE": "string",
    "SINGLE_SELECT": "string",
    "MULTI_SELECT": "string[]",
    "RECORD_SINGLE_SELECT": "string",
    "RECORD_MULTI_SELECT": "string[]",
    "FORM_SINGLE_SELECT": "string",
    "OBJECT_SINGLE_SELECT": "string",
    "OBJECT_MULTI_SELECT": "string[]",
    # Resolved to the record's value, whose type depends on the property.
    "PROPERTY_SINGLE_SELECT": "string | number | boolean",
    "PROPERTY_MULTI_SELECT": "Array<string | number | boolean>",
    "SWITCH": "boolean",
    "MAPPING": "Record<string, unknown>",
    "FILE": "string",
    "MULTI_FILE": "string[]",
    "IMAGE": "string",
    "COLOR": "string",
}

_ALWAYS_PRESENT = {"SWITCH", "MULTI_SELECT", "MULTI_FILE", "RECORD_MULTI_SELECT", "OBJECT_MULTI_SELECT", "REPEATABLE"}


def _pascal_case(value: str) -> str:
    return "".join(part.capitalize() for part in value.replace("-", "_").split("_") if part)


def _literal_union(options: list[Any]) -> str | None:
    """Narrow a select field to its declared options."""
    names = [str(o.get("name")) for o in options if isinstance(o, dict) and o.get("name")]
    if not names:
        return None
    return " | ".join(f"'{name}'" for name in names)


def _field_type(item: dict[str, Any]) -> str:
    field_type = str(item.get("type") or "").upper()
    options = item.get("options")

    if field_type == "SINGLE_SELECT" and isinstance(options, list):
        union = _literal_union(options)
        if union:
            return union

    if field_type == "MULTI_SELECT" and isinstance(options, list):
        union = _literal_union(options)
        if union:
            return f"Array<{union}>"

    if field_type == "REPEATABLE":
        nested = item.get("itemFields")
        if isinstance(nested, list) and nested:
            parts: list[str] = []
            for child in nested:
                if not isinstance(child, dict):
                    continue
                child_name = str(child.get("name") or "").strip()
                if not child_name:
                    continue
                child_type = _field_type(child)
                child_kind = str(child.get("type") or "").upper()
                child_nullable = (
                    not child.get("required")
                    or bool(child.get("visibleWhen"))
                ) and child_kind not in _ALWAYS_PRESENT
                parts.append(
                    f"{child_name}: {child_type}{' | null' if child_nullable else ''}"
                )
            if parts:
                return f"Array<{{ {'; '.join(parts)} }}>"
        return "Array<Record<string, unknown>>"

    return _FIELD_TS_TYPES.get(field_type, "unknown")


def _doc_comment(item: dict[str, Any], indent: str) -> list[str]:
    lines: list[str] = []
    label = str(item.get("label") or "").strip()
    help_text = str(item.get("helpText") or "").strip()
    field_type = str(item.get("type") or "").upper()

    body: list[str] = []
    if label:
        body.append(label)
    if help_text:
        body.append(help_text)
    if field_type.startswith("PROPERTY_"):
        body.append(
            "Resolved to the value of the chosen property on this page's record. "
            "Use `rawFields` for the property name itself."
        )
    if item.get("visibleWhen"):
        body.append("Null when its visibility conditions do not hold.")

    if not body:
        return lines

    if len(body) == 1:
        return [f"{indent}/** {body[0]} */"]

    lines.append(f"{indent}/**")
    for index, paragraph in enumerate(body):
        if index:
            lines.append(f"{indent} *")
        lines.append(f"{indent} * {paragraph}")
    lines.append(f"{indent} */")
    return lines


def render_module_types(module: LocalModule) -> str:
    """Render the contents of a module's ``fields.d.ts``."""
    interface = f"{_pascal_case(module.name)}Fields"
    lines = [
        "/*",
        " * GENERATED by `caraer apps validate` / `caraer apps push` - do not edit.",
        " *",
        f" * Field types for the '{module.name}' module, derived from",
        " * the manifest in index.astro. Regenerate after changing the field list.",
        " */",
        "",
        f"export interface {interface} {{",
    ]

    for item in module.field_entries:
        name = str(item.get("name") or "").strip()
        if not name:
            continue

        lines.extend(_doc_comment(item, "  "))

        field_type = str(item.get("type") or "").upper()
        ts_type = _field_type(item)

        # A hidden or conditionally hidden field resolves to null, and an
        # optional one may never be filled. Encoding that in the type is what
        # stops a module rendering "undefined" on a live site.
        nullable = (
            not item.get("required")
            or bool(item.get("visibleWhen"))
        ) and field_type not in _ALWAYS_PRESENT

        lines.append(f"  {name}: {ts_type}{' | null' if nullable else ''};")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def write_module_types(module: LocalModule) -> Path:
    """Write ``types.d.ts`` for one module, returning its path."""
    target = module.directory / GENERATED_TYPES_FILE
    target.write_text(render_module_types(module), encoding="utf-8")
    legacy = module.directory / "fields.d.ts"
    if legacy.exists() and legacy != target:
        try:
            legacy.unlink()
        except OSError:
            pass
    return target


def generate_module_types(root: Path, config: ProjectConfig) -> list[Path]:
    """Regenerate declarations for every module in the workspace."""
    written: list[Path] = []
    for module in discover_local_modules(root, config):
        if module.config:
            written.append(write_module_types(module))
    return written
