"""Generate typed helpers for Caraer serverless function payloads."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Literal

from caraer_cli.project.schema import ProjectConfig

RuntimeKind = Literal["nodejs", "python"]

TYPESCRIPT_FILENAME = "caraer.d.ts"
PYTHON_FILENAME = "caraer_types.py"


def resolve_runtime_kind(runtime: str | None) -> RuntimeKind:
    text = (runtime or "nodejs22").strip().lower()
    if text.startswith("python"):
        return "python"
    return "nodejs"


def types_dir(root: Path, config: ProjectConfig) -> Path:
    return root / config.srcDir / "types"


def typegen_output_path(root: Path, config: ProjectConfig) -> Path:
    kind = resolve_runtime_kind(config.runtime)
    base = types_dir(root, config)
    if kind == "python":
        return base / PYTHON_FILENAME
    return base / TYPESCRIPT_FILENAME


def generate_types(
    root: Path,
    config: ProjectConfig,
    *,
    force: bool = False,
) -> dict[str, Any]:
    """Write typed helpers under ``src/types/`` for the app runtime."""
    kind = resolve_runtime_kind(config.runtime)
    out = typegen_output_path(root, config)
    if out.exists() and not force:
        raise FileExistsError(
            f"Typegen output already exists: {out}. Use --force to overwrite."
        )
    out.parent.mkdir(parents=True, exist_ok=True)
    if kind == "python":
        out.write_text(_python_types(), encoding="utf-8")
    else:
        out.write_text(_typescript_types(), encoding="utf-8")
    return {
        "path": out,
        "runtime": kind,
        "relative": str(out.relative_to(root)),
    }


def _typescript_types() -> str:
    return '''\
/**
 * Generated by `caraer apps typegen`. Do not edit by hand.
 *
 * Common serverless / installation payload shapes for Caraer apps.
 */

/** Installation settings field as delivered in lifecycle / webhook bodies. */
export interface SettingFieldValue {
  name: string;
  label?: string;
  type?: string;
  value?: unknown;
  defaultValue?: unknown;
  hasValue?: boolean;
}

/** Approximate lifecycle hook body (install / update / uninstall / rotate). */
export interface LifecyclePayload {
  event?: "Installed" | "Updated" | "Uninstalled" | "Rotated" | string;
  timestamp?: number;
  appUuid?: string;
  appName?: string;
  appLabel?: string;
  privateApp?: boolean;
  authMethod?: "OAUTH2" | "API_KEY" | string;
  userUuid?: string;
  companyUuid?: string;
  installationToken?: string;
  oauthConnected?: boolean;
  settingsSchema?: SettingFieldValue[];
  scopes?: string[];
  settingsChanged?: boolean;
  scopesChanged?: boolean;
  filtersChanged?: boolean;
  [key: string]: unknown;
}

/** Record / domain webhook body (USER_FRIENDLY shape varies by topic). */
export interface WebhookPayload {
  topic?: string;
  event?: string;
  timestamp?: number;
  appUuid?: string;
  companyUuid?: string;
  installationToken?: string;
  record?: Record<string, unknown>;
  objectName?: string;
  settingsSchema?: SettingFieldValue[];
  [key: string]: unknown;
}

/** Cron / schedule invocation body. */
export interface SchedulePayload {
  scheduleName?: string;
  name?: string;
  appUuid?: string;
  companyUuid?: string;
  installationToken?: string;
  scheduledAt?: string | number;
  settingsSchema?: SettingFieldValue[];
  [key: string]: unknown;
}

/** Inbound HTTP route body (provider-specific; wrapped by the platform). */
export interface InboundPayload {
  appUuid?: string;
  companyUuid?: string;
  installationToken?: string;
  routeName?: string;
  body?: unknown;
  headers?: Record<string, string>;
  [key: string]: unknown;
}

/** Async installation job payload (function receives this as req.body). */
export interface JobPayload {
  jobId?: string;
  functionName?: string;
  appUuid?: string;
  companyUuid?: string;
  installationToken?: string;
  [key: string]: unknown;
}

/** Installation state document (arbitrary JSON map). */
export type InstallationState = Record<string, unknown>;

/** Installation secrets map (values are strings when readable). */
export type InstallationSecrets = Record<string, string>;

/** POST /installation/jobs request body. */
export interface EnqueueJobRequest {
  functionName: string;
  payload?: Record<string, unknown>;
  delaySeconds?: number;
}

/** Installation job status document. */
export interface InstallationJob {
  jobId: string;
  status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | string;
  functionName?: string;
  payload?: Record<string, unknown>;
  result?: unknown;
  error?: string;
  createdAt?: string | number;
  updatedAt?: string | number;
  [key: string]: unknown;
}

/** Wrapper returned by many Caraer API endpoints. */
export interface ApiSuccess<T = unknown> {
  message?: string;
  data?: T;
}
'''


def _python_types() -> str:
    return '''\
"""Generated by `caraer apps typegen`. Do not edit by hand.

Common serverless / installation payload shapes for Caraer apps.
"""

from __future__ import annotations

from typing import Any, NotRequired, TypedDict


class SettingFieldValue(TypedDict, total=False):
    name: str
    label: str
    type: str
    value: Any
    defaultValue: Any
    hasValue: bool


class LifecyclePayload(TypedDict, total=False):
    event: str
    timestamp: int | float
    appUuid: str
    appName: str
    appLabel: str
    privateApp: bool
    authMethod: str
    userUuid: str
    companyUuid: str
    installationToken: str
    oauthConnected: bool
    settingsSchema: list[SettingFieldValue]
    scopes: list[str]
    settingsChanged: bool
    scopesChanged: bool
    filtersChanged: bool


class WebhookPayload(TypedDict, total=False):
    topic: str
    event: str
    timestamp: int | float
    appUuid: str
    companyUuid: str
    installationToken: str
    record: dict[str, Any]
    objectName: str
    settingsSchema: list[SettingFieldValue]


class SchedulePayload(TypedDict, total=False):
    scheduleName: str
    name: str
    appUuid: str
    companyUuid: str
    installationToken: str
    scheduledAt: str | int | float
    settingsSchema: list[SettingFieldValue]


class InboundPayload(TypedDict, total=False):
    appUuid: str
    companyUuid: str
    installationToken: str
    routeName: str
    body: Any
    headers: dict[str, str]


class JobPayload(TypedDict, total=False):
    jobId: str
    functionName: str
    appUuid: str
    companyUuid: str
    installationToken: str


InstallationState = dict[str, Any]
InstallationSecrets = dict[str, str]


class EnqueueJobRequest(TypedDict):
    functionName: str
    payload: NotRequired[dict[str, Any]]
    delaySeconds: NotRequired[float]


class InstallationJob(TypedDict, total=False):
    jobId: str
    status: str
    functionName: str
    payload: dict[str, Any]
    result: Any
    error: str
    createdAt: str | int | float
    updatedAt: str | int | float
'''
