/*
 * GENERATED by `caraer apps validate` / `caraer apps push` - do not edit.
 *
 * Field types for the 'hello_world' module, derived from
 * the manifest in index.astro. Regenerate after changing the field list.
 */

export interface HelloWorldFields {
  /** Heading */
  heading: string;
  /**
   * Text
   *
   * Markdown is supported.
   */
  body: string | null;
}
