/**
 * Generated by `caraer apps typegen`. Do not edit by hand.
 *
 * Common serverless / installation payload shapes for Caraer apps.
 */

/** Installation settings field as delivered in lifecycle / webhook bodies. */
export interface SettingFieldValue {
  name: string;
  label?: string;
  type?: string;
  value?: unknown;
  defaultValue?: unknown;
  hasValue?: boolean;
}

/** Approximate lifecycle hook body (install / update / uninstall / rotate). */
export interface LifecyclePayload {
  event?: "Installed" | "Updated" | "Uninstalled" | "Rotated" | string;
  timestamp?: number;
  appUuid?: string;
  appName?: string;
  appLabel?: string;
  privateApp?: boolean;
  authMethod?: "OAUTH2" | "API_KEY" | string;
  userUuid?: string;
  companyUuid?: string;
  installationToken?: string;
  oauthConnected?: boolean;
  settingsSchema?: SettingFieldValue[];
  scopes?: string[];
  settingsChanged?: boolean;
  scopesChanged?: boolean;
  filtersChanged?: boolean;
  [key: string]: unknown;
}

/** Record / domain webhook body (USER_FRIENDLY shape varies by topic). */
export interface WebhookPayload {
  topic?: string;
  event?: string;
  timestamp?: number;
  appUuid?: string;
  companyUuid?: string;
  installationToken?: string;
  record?: Record<string, unknown>;
  objectName?: string;
  settingsSchema?: SettingFieldValue[];
  [key: string]: unknown;
}

/** Cron / schedule invocation body. */
export interface SchedulePayload {
  scheduleName?: string;
  name?: string;
  appUuid?: string;
  companyUuid?: string;
  installationToken?: string;
  scheduledAt?: string | number;
  settingsSchema?: SettingFieldValue[];
  [key: string]: unknown;
}

/** Inbound HTTP route body (provider-specific; wrapped by the platform). */
export interface InboundPayload {
  appUuid?: string;
  companyUuid?: string;
  installationToken?: string;
  routeName?: string;
  body?: unknown;
  headers?: Record<string, string>;
  [key: string]: unknown;
}

/** Async installation job payload (function receives this as req.body). */
export interface JobPayload {
  jobId?: string;
  functionName?: string;
  appUuid?: string;
  companyUuid?: string;
  installationToken?: string;
  [key: string]: unknown;
}

/** Installation state document (arbitrary JSON map). */
export type InstallationState = Record<string, unknown>;

/** Installation secrets map (values are strings when readable). */
export type InstallationSecrets = Record<string, string>;

/** POST /installation/jobs request body. */
export interface EnqueueJobRequest {
  functionName: string;
  payload?: Record<string, unknown>;
  delaySeconds?: number;
}

/** Installation job status document. */
export interface InstallationJob {
  jobId: string;
  status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | string;
  functionName?: string;
  payload?: Record<string, unknown>;
  result?: unknown;
  error?: string;
  createdAt?: string | number;
  updatedAt?: string | number;
  [key: string]: unknown;
}

/** Wrapper returned by many Caraer API endpoints. */
export interface ApiSuccess<T = unknown> {
  message?: string;
  data?: T;
}
